import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { AiContentSource } from "@/lib/exam-service/types";

const AI_BADGE_LABELS: Record<Exclude<AiContentSource, "fallback">, string> = {
	ollama: "Generated by Ollama",
	gemini: "AI Generated",
	"cf-ai": "AI Generated",
};

export function AiContentBadge({
	className,
	source,
}: {
	className?: string;
	source?: AiContentSource | null;
}) {
	if (!source || source === "fallback") {
		return null;
	}

	return (
		<Badge
			variant="outline"
			className={cn(
				"gap-1.5 border-sky-200 bg-sky-50 text-sky-700",
				className,
			)}
		>
			<Sparkles className="h-3 w-3" />
			{AI_BADGE_LABELS[source]}
		</Badge>
	);
}
