export * from "./tables/aiExamTemplates";
export * from "./tables/aiExamQuestionTemplates";
export * from "./tables/classrooms";
export * from "./tables/examSchedules";
export * from "./tables/exams";
export * from "./tables/examQuestions";
export * from "./tables/masterTimetable";
export * from "./tables/newExams";
export * from "./tables/newExamQuestions";
